#!/usr/bin/env python
# -*- coding: utf-8 -*-
# dicompyler
"""Script to start dicompyler from source."""
# Copyright (c) 2009-2017 Aditya Panchal
# This file is part of dicompyler, relased under a BSD license.
#    See the file license.txt included with this distribution, also
#    available at https://github.com/bastula/dicompyler/

import dicompyler.main

dicompyler.main.start()
